### ISSUE TITLE
Error adding: printer (1280, u’server-error-internal-error’) > copy_model: empty PPD file

### ISSUE THREAD

**Issue by elsguns** [simoncadman/CUPS-Cloud-Print#100]
Hi, would it be possible Google changed the data format to generate the ppd files? 
tnx,
Els

**Comment by DemonWav** [comment]
I was getting this error too. If you use the capabilities-fix branch it will work.

**Comment by elsguns** [comment]
Ok, great, applied the fix and everything is working perfectly fine again! :-)

**Comment by simoncadman** [comment]
I've released a new version of CUPS Cloud Print ( 20160502 ), should all be working again with this release.

Thanks
