### ISSUE TITLE
New OSX Package doesn't install

### ISSUE THREAD

**Issue by amaccuish** [simoncadman/CUPS-Cloud-Print#101]
Just tried the latest OSX package with the capabilities fixes but it refuses to install with "The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance."

**Comment by simoncadman** [comment]
Hi,

Which version of OS X are you trying to install it on?

Thanks

**Comment by amaccuish** [comment]
Hi

10.11 el capitan

Thanks :)

**Comment by amaccuish** [comment]
After much playing about I found httplib2 wasn't properly installed the the installer validation script, reinstalled and now all working! Sorry to bother! Cheers for the great software!
