### ISSUE TITLE
Error 1280 adding printers with release 20160502, OSX 10.11 El Capitan

### ISSUE THREAD

**Issue by eeconn** [simoncadman/CUPS-Cloud-Print#103]
I installed release 20160502 using the source install instructions at https://www.niftiestsoftware.com/cups-cloud-print/

Output from setupcloudprint.py:
`[username@host] /usr/local/share/cloudprint-cups$ sudo ./setupcloudprint.py`
`Name for this user account ( eg something@gmail.com )? gmailID@gmail.com`
`Open this URL, grant access to CUPS Cloud Print,then provide the code displayed:`

`https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudprint&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=843805314553.apps.googleusercontent.com&access_type=offline`

`Code from Google: *********************************************`

`You currently have these accounts configured:`
`gmailID@gmail.com`
`Add more accounts (Y/N)? n`
`Add all Google Cloud Print printers from gmailID@gmail.com to CUPS (Y/N)? y`
`Use a prefix for names of created printers (Y/N)? n`
`Error adding: obake (1280, u'server-error-internal-error')`
`Error adding: Save_to_Google_Drive (1280, u'server-error-internal-error')`
`Added 2 new printers to CUPS`

Attaching the output of reportissues.py.
[cloudprint_error_report.txt](https://github.com/simoncadman/CUPS-Cloud-Print/files/252893/cloudprint_error_report.txt) 
For the printer named "obake", the result of cupstestppd was 4, with failure messages about bad duplex choices and a warning about the length of the PCFileName. For "Save to Google Drive" the result of cupstestppd is 0 and there's just a warning about the length of the filename, but adding the destination still fails.

**Comment by simoncadman** [comment]
Hi,

I've just released an updated package which should now fix this:

https://niftyrepo.niftiestsoftware.com/cups-cloud-print/packages/cupscloudprint-20160521.pkg

I had to move the scripts from /usr/local/share/ to /Library/ to prevent issues with CUPS sandboxing in El Capitan, seems to work now on my test machines.

Thanks

Simon
