### ISSUE TITLE
Error adding: OASE (1280, u'server-error-internal-error')

### ISSUE THREAD

**Issue by dviersel** [simoncadman/CUPS-Cloud-Print#76]
Hi Simon, 

Great utility, I think. I tried several times, through various accounts, to add my HP Officejet Pro 276dw MFP but I keep getting this error message. I pinned it down to the following line in printermanager.py:

 result = connection.addPrinter(
                name=printername, ppdname=printerppdname, info=printername,
                location=location, device=printer.getURI())
 
I am using the latest version from the ppa repository.

-Dylan

The output from reportissues: 

"cupscloudprint:snippet%40gmail.com:2ab_xyryqrgqkiqbr6ngnq.ppd" en "Google" "OASE (snippet@gmail.com)" "MFG:Google;DRV:GCP;CMD:POSTSCRIPT;DES:GoogleCloudPrint;MDL:gcp://snippet%40gmail.com/2ab_xyryqrgqkiqbr6ngnq"

{u'status': u'', u'isTosAccepted': False, u'updateTime': u'1405260230643', u'gcpVersion': u'1.0', u'description': u'', u'name': u'HP Officejet Pro 276dw MFP', u'tags': [u'^recent', u'^own', u'^can_share', u'^can_update', u'^can_delete'], u'defaultDisplayName': u'OASE', u'accessTime': u'1405256510781', u'connectionStatus': u'UNKNOWN', u'id': u'2ab_xyryqrgqkiqbr6ngnq', u'ownerName': u'snippet', u'capsHash': u'', u'displayName': u'OASE', u'ownerId': u'snippet@gmail.com', u'type': u'HP', u'createTime': u'1405256510781', u'proxy': u'HP'}
[{u'type': u'Feature', u'displayName': u'Colors', u'name': u'ns1:Colors', u'options': [{u'default': True, u'displayName': u'Grey_CMY', u'name': u'Grey_CMY'}, {u'displayName': u'Grey_K', u'name': u'Grey_K'}, {u'displayName': u'Color', u'name': u'Color'}]}, {u'type': u'ParameterDef', u'displayName': u'Copies', u'name': u'hpcopies'}, {u'type': u'Feature', u'displayName': u'PrintQualities', u'name': u'ns1:PrintQualities', u'options': [{u'default': True, u'displayName': u'Normal', u'name': u'Normal'}, {u'displayName': u'Best', u'name': u'Best'}, {u'displayName': u'FastDraft', u'name': u'FastDraft'}]}, {u'type': u'Feature', u'displayName': u'Plex', u'name': u'ns1:Plex', u'options': [{u'displayName': u'None', u'name': u'None'}, {u'default': True, u'displayName': u'Duplex', u'name': u'Duplex'}]}, {u'type': u'Feature', u'displayName': u'InputBins', u'name': u'ns1:InputBins', u'options': [{u'displayName': u'Main', u'name': u'Main', u'default': True, u'Plex': u'Duplex', u'MediaTypesSupported': u'HPGlossy220,Plain,Unknown', u'MediaSizeNamesSupported': u'JisB5_182x257mm,Unknown,NaIndex_4x6_4x6in,JpnChou3_120x235mm,NaIndex_3x5_3x5in,JpnChou4_90x205mm,IsoA4_210x297mm,NaInvoice_5.5x8.5in,NaLegal_8.5x14in,IsoA6_105x148mm,IsoDl_110x220mm,Na_5x7_5x7in,NaIndex_5x8_5x8in,IsoC5_162x229mm,oe_photo-l_3.5x5in,JpnOufuku_148x200mm,OmSmallPhoto_100x150mm,NaMonarch_3.875x7.5in,JpnHagaki_100x148mm,NaGovtLetter_8x10in,NaExecutive_7.25x10.5in,NaLetter_8.5x11in,IsoC6_114x162mm,IsoB5_176x250mm', u'InputBinType': u'GenericMedia'}, {u'displayName': u'Auto', u'name': u'Auto', u'MediaTypesSupported': u'Plain,Unknown,HPGlossy220', u'Plex': u'Duplex', u'MediaSizeNamesSupported': u'oe_photo-l_3.5x5in,IsoA6_105x148mm,IsoC6_114x162mm,NaIndex_4x6_4x6in,NaLegal_8.5x14in,IsoB5_176x250mm,JpnHagaki_100x148mm,Unknown,IsoA4_210x297mm,NaIndex_3x5_3x5in,NaInvoice_5.5x8.5in,NaLetter_8.5x11in,JpnChou3_120x235mm,IsoC5_162x229mm,JpnChou4_90x205mm,NaMonarch_3.875x7.5in,JisB5_182x257mm,NaGovtLetter_8x10in,IsoDl_110x220mm,JpnOufuku_148x200mm,NaExecutive_7.25x10.5in,OmSmallPhoto_100x150mm,Na_5x7_5x7in,NaIndex_5x8_5x8in', u'InputBinType': u'GenericMedia'}, {u'displayName': u'Alternate', u'name': u'Alternate', u'MediaTypesSupported': u'Unknown,HPGlossy220,Plain', u'Plex': u'Duplex', u'MediaSizeNamesSupported': u'NaLetter_8.5x11in,NaLegal_8.5x14in,IsoA4_210x297mm', u'InputBinType': u'GenericMedia'}]}, {u'type': u'Feature', u'displayName': u'Margins', u'name': u'ns1:Margins', u'options': [{u'default': True, u'displayName': u'MarginLess', u'name': u'MarginLess'}]}]

Result of cupstestppd was 0
/tmp/.ppdfile: PASS
        WARN    PCFileName longer than 8.3 in violation of PPD spec.
                REF: Pages 61-62, section 5.3.

"cupscloudprint:snippet%40gmail.com:__google__docs.ppd" en "Google" "Opslaan in Google Drive (snippet@gmail.com)" "MFG:Google;DRV:GCP;CMD:POSTSCRIPT;DES:GoogleCloudPrint;MDL:gcp://snippet%40gmail.com/__google__docs"

{u'status': u'', u'isTosAccepted': False, u'updateTime': u'1370287324050', u'gcpVersion': u'1.0', u'description': u'Je document opslaan als pdf in Google Drive', u'name': u'Save to Google Docs', u'tags': [u'^recent', u'__google__drive_enabled', u'save', u'docs', u'pdf', u'google'], u'defaultDisplayName': u'Opslaan in Google Drive', u'accessTime': u'1316132041869', u'connectionStatus': u'ONLINE', u'id': u'__google__docs', u'ownerName': u'Cloud Print', u'capsHash': u'', u'displayName': u'Opslaan in Google Drive', u'ownerId': u'cloudprinting@gmail.com', u'type': u'DRIVE', u'createTime': u'1311368403894', u'proxy': u'google-wide'}
[{u'type': u'ParameterDef', u'psf:DataType': u'xsd:string', u'psk:DisplayName': u'Google Drive File Name', u'name': u'__goog__drive_file_name'}]

Result of cupstestppd was 0
/tmp/.ppdfile: PASS
        WARN    PCFileName longer than 8.3 in violation of PPD spec.
                REF: Pages 61-62, section 5.3.

**Comment by GrayMatter** [comment]
I received the same errors as the OP.  I found that they showed up after restarting CUPS even though the logs had the internal errors reported.

**Comment by simoncadman** [comment]
Ok thanks, any logs you can provide would be useful - if possible could you please enable debug logging in CUPS ( set LogLevel to debug in /etc/cups/cupsd.conf and restart cups ), and get the CUPS error log? I'm hoping that will give more useful information.

Thanks

**Comment by Thomas-Tsai** [comment]
another 1280 error, and check cups/error.log found permission deny
i use root/sudo to add print via setupcloudprint.py

D [20/Jan/2015:11:48:35 +0800] [CGI] self._context.load_verify_locations(ca_certs)
D [20/Jan/2015:11:48:35 +0800] [CGI] IOError: [Errno 13] Permission denied
E [20/Jan/2015:11:48:35 +0800] copy_model: empty PPD file
D [20/Jan/2015:11:48:35 +0800] CUPS-Add-Modify-Printer server-error-internal-error: Unable to copy PPD file.
E [20/Jan/2015:11:48:35 +0800] [Client 15] Returning IPP server-error-internal-error for CUPS-Add-Modify-Printer (ipp://localhost/printers/HC_R
319_KONICA_MINOLTA_423_PCL) from localhost
D [20/Jan/2015:11:48:35 +0800] [Client 15] Content-Length: 118

any suggestion ?

**Comment by simoncadman** [comment]
Hi Thomas-Tsai,

That sounds like the CCP backend is unable to read your certificate store, so it's unable to verify Google's HTTPS certificate, which distribution are you using, and are you aware of any extra security features or modules you have enabled ( SELinux, apparmor etc )?

Thanks

**Comment by jameshilliard** [comment]
I think I may have the same error, here's my log https://gist.github.com/jameshilliard/c731694ea7290a197e84
And I'm seeing this error in my cups error log:
E [12/May/2015:15:30:25 -0600] [Client 154] Returning IPP server-error-internal-error for CUPS-Add-Modify-Printer (ipp://localhost/printers/Brother%5FQL-700) from localhost
E [12/May/2015:15:30:25 -0600] copy_model: empty PPD file

**Comment by simoncadman** [comment]
Hi @jameshilliard,

I believe that's a known issue specific to OS X Yosemite, I now have access to a machine with that OS and I'm able to reproduce it.

Thanks

Simon

**Comment by GStainburn** [comment]
I've got an old server running Fedora 19 and with cloudPrint installed from the instructions at https://www.niftiestsoftware.com/cups-cloud-print/ many moons ago.  It's been working fine until today.

I have a number of printers that only have Windows drivers so I use CloudPrint to print to them from Linux.  Periodically when I reboot the Win7 PC, it *detects* the existing printer as a new one, and stops the old one working.  I then have to tidy up by deleting the old one, renaming the new one and then checking all preferences etc.  I have to do this about once a month.

Once the Windows PC is correct again, I then delete and re-create them in Google Cloud Print, which worked fine.

I then tried to update my Linux box. When I did this, I got the above 1280 error for each of the printers:

[root@lou ~]# /usr/share/cloudprint-cups/setupcloudprint.py
You currently have these accounts configured: 
******.*****@******
Add more accounts (Y/N)? n
Add all Google Cloud Print printers from ******.*****@****** (Y/N)? n
Not adding printers automatically
1) ValuePlusSvc
2) Leeds showroom copier 2
3) ValuePlusKia
4) ValuePlusFord
5) Call Centre HP
6) Save to Google Drive
7) OKI_C511
8) OKI C511
Add printer (1-8, 0 to cancel)? 3
Adding ValuePlusKia
Use a prefix for name of printer (Y/N)? n
Error adding: ValuePlusKia (1280, 'server-error-internal-error')
1) ValuePlusSvc
2) Leeds showroom copier 2
3) ValuePlusKia
4) ValuePlusFord
5) Call Centre HP
6) Save to Google Drive
7) OKI_C511
8) OKI C511
Add printer (1-8, 0 to cancel)? 

[root@lou ~]# tail -f /var/log/cups/error_log
E [17/Mar/2016:11:28:54 +0000] copy_model: empty PPD file
E [17/Mar/2016:11:28:54 +0000] Returning IPP server-error-internal-error for CUPS-Add-Modify-Printer (ipp://localhost/printers/ValuePlusKia) from localhost
^C
[root@lou ~]# 

Any suggestions on what I can do to fix this?

Thanks.

Gary

**Comment by ericmarston** [comment]
I am also suddenly having the same problem. A few hours ago a config that has been running for many months stopped working. I have tried completely removing and uninstalling and reinstalling and nothing is working. 

I am getting the same errors when trying to add the printers as above. 

Returning IPP server-error-internal-error for CUPS-Add-Modify-Printer (ipp://localhost/printers/HP%5F
LJ%5FP4010%5FP4510%5FSeries%5FPCL%5F6%5F1) from localhost
E [17/Mar/2016:17:25:16 +0000] copy_model: empty PPD file!

Before doing the uninstall/reinstall of cups and cupscloudprint, the printers were "disabled" and lpstat was showing this:

printer HP_LJ_P4010_P4510_Series_PCL_6_1 disabled since Wed 16 Mar 2016 10:10:02 PM UTC -
	/usr/lib/cups/backend/gcp failed

Please help.

**Comment by ericmarston** [comment]
As a follow up, I created a completely fresh Ubuntu server (previously using CentOS) and installed completely fresh and had the same error when trying to add printers. Wondering if Google is blocking something.

**Comment by GStainburn** [comment]
I continued working on this yesterday. I 
removed all the affected printers from my Google account, 
removed them from the PC, 
re-installed them on the PC
Re-added them to my Google account
removed them from my F19 box
re-ran setupcloudprint.py
got the same errors.

Installed everything on a F21 box with the same problems.
When I got home I tried the same process on my F21 laptop using my home network and got the same results.

**Comment by amaccuish** [comment]
I am also having the same problem: "Error adding: Save_to_Google_Drive (1280, u'server-error-internal-error')"

I thought it was at first a problem with Mac OSX sandboxing, I saw messages in the system logs, but I disabled it for CUPS temporarily and still having this problem.

**Comment by simoncadman** [comment]
I've released a new version of CUPS Cloud Print ( 20160502 ), should all be working again with this release.

Thanks
