### ISSUE TITLE
CUPS Cloud Print no longer supports printing files directly for security reasons

### ISSUE THREAD

**Issue by srugai** [simoncadman/CUPS-Cloud-Print#84]
Hi Simon,
Just installed CUPS Cloud Print on Ubuntu 14.04 LTS. It works like a charm. Typing lp -d myprintername myfilename and there it go.

On the other hand installing on Centos 7 via .rpm I manage to import the printers and everything seems ok with lpstat -t and so, but, typing lp -d myprintername myfilename I got the message "Sorry! CUPS Cloud Print no longer supports printing files directly for security reasons". The printers appears as "Local Raw Printer" in the cups web management tool "make and model" column, although it cons as "Google Cloud Print, 1.0" in the /etc/cups/printers.conf.

One thing I did only in the Centos 7 box was edit the /etc/cups/printers.conf and change the printer name. Cups was stopped at the time.
Thanks,

**Comment by simoncadman** [comment]
Hi srugai,

I've just done a fresh install on a CentOS 7 VM, and it all seemed to work correctly using the instructions on https://www.niftiestsoftware.com/cups-cloud-print/ :

https://gist.github.com/simoncadman/96608d9f45769adf85c1

Did you install using the RPM repo, and did you use the setup script? As the gist above shows, I can't see any problems on CentOS 7, and I didn't have any need to change anything in the printers.conf file.

Thanks

Simon

**Comment by srugai** [comment]
Thanks Simon for the prompt answer.

The problem is solved.

Yes, I'v used RPM and the instructions. The only thing I did, before trying
to print a file, was rename the printers spool name in the printers.conf. I
want an specific spool name and
the script imports the printer as it is defined in the windows machine used
to share it via google print.

Changing the printers.conf was the source of the problem. The same name is
needed in both ends.

rgds,


On 29 June 2015 at 05:02, Simon Cadman <notifications@github.com> wrote:

> Hi srugai,
>
> I've just done a fresh install on a CentOS 7 VM, and it all seemed to work
> correctly using the instructions on
> https://www.niftiestsoftware.com/cups-cloud-print/ :
>
> https://gist.github.com/simoncadman/96608d9f45769adf85c1
>
> Did you install using the RPM repo, and did you use the setup script? As
> the gist above shows, I can't see any problems on CentOS 7, and I didn't
> have any need to change anything in the printers.conf file.
>
> Thanks
>
> Simon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simoncadman/CUPS-Cloud-Print/issues/84#issuecomment-116319645>
> .
>



-- 

Arnaldo Rugai


This email may contain privileged and  confidential  information intended
only for the use of the addressee named above.
No liability is accepted for the accuracy or integrity of the information
contained herein or for any delays, interruptions, errors or omissions
however occurring.
If you are not the intended recipient of  this email, you  are  hereby
notified  that  any  use,  dissemination, distribution or reproduction of
this email is prohibited.

**Comment by simoncadman** [comment]
Ok great, glad it's working now.

Thanks
