### ISSUE TITLE
Error adding: EPSON_XP-420_Series_EPSON3E7898 (1280, u'server-error-internal-error')

### ISSUE THREAD

**Issue by nbecker** [simoncadman/CUPS-Cloud-Print#99]
Used to work, but has stopped working.  I tried deleting/re-adding printers.  I get:
Error adding: EPSON_XP-420_Series_EPSON3E7898 (1280, u'server-error-internal-error')

I have disabled my firewall - so that's not the issue.

This is fedora 23 (all updates).

I tried removing /etc/cloudprinter.conf and re-running 
sudo /usr/share/cloudprint-cups/setupcloudprint.py

no difference.

**Comment by azizLIGHT** [comment]
For a quick fix to get printing going:
Add `self._fields['capabilities'] = {}` to /usr/share/cloudprint-cups/printer.py and run /usr/share/cloudprint-cups/upgrade.py (or delete your printers and re-run setupcloudprint.py)
[source](https://github.com/simoncadman/CUPS-Cloud-Print/issues/96#issuecomment-198936991)

For proper fix:
use the capabilities-fix branch

**Comment by simoncadman** [comment]
I've released a new version of CUPS Cloud Print ( 20160502 ), should all be working again with this release.

Thanks
